// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_nIo8H7rlaKTg5QftKRHLE5qHHhDOEdE',
    appId: '1:197588704936:web:695916662f05ccb848ec9d',
    messagingSenderId: '197588704936',
    projectId: 'quickstart-1559620949642',
    authDomain: 'quickstart-1559620949642.firebaseapp.com',
    storageBucket: 'quickstart-1559620949642.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5jLicYZwnEMUc0viuFiJ-Bam8SHC2i68',
    appId: '1:197588704936:android:bfaa56f06e6b4ad248ec9d',
    messagingSenderId: '197588704936',
    projectId: 'quickstart-1559620949642',
    storageBucket: 'quickstart-1559620949642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMra7WUNlnHyBq4zOByNzuUFQJ8QdhjMQ',
    appId: '1:197588704936:ios:86649e4cd7a7123548ec9d',
    messagingSenderId: '197588704936',
    projectId: 'quickstart-1559620949642',
    storageBucket: 'quickstart-1559620949642.appspot.com',
    iosBundleId: 'com.example.template',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMra7WUNlnHyBq4zOByNzuUFQJ8QdhjMQ',
    appId: '1:197588704936:ios:86649e4cd7a7123548ec9d',
    messagingSenderId: '197588704936',
    projectId: 'quickstart-1559620949642',
    storageBucket: 'quickstart-1559620949642.appspot.com',
    iosBundleId: 'com.example.template',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_nIo8H7rlaKTg5QftKRHLE5qHHhDOEdE',
    appId: '1:197588704936:web:1521499b64d93e4748ec9d',
    messagingSenderId: '197588704936',
    projectId: 'quickstart-1559620949642',
    authDomain: 'quickstart-1559620949642.firebaseapp.com',
    storageBucket: 'quickstart-1559620949642.appspot.com',
  );
}
